### ISSUE TITLE
Issue with accuracy

### ISSUE THREAD

**Issue by stencilman** [MatthieuCourbariaux/deep-learning-storage#3]
Hi, [here](https://github.com/MatthieuCourbariaux/deep-learning-multipliers/blob/master/format.py#L64) it should be .clip(value, -max, max-1). Also, only your inputs, weights and outputs are fixed points. The internal accumulation while doing say the convolution is still float32. If you use a big accumulator, say 40 bits, you will get very similar results as floats, but floats will make approximations and the two results will not be exactly the same.

**Comment by MatthieuCourbariaux** [comment]
Actually, I think we are already computing the -1 [there](https://github.com/MatthieuCourbariaux/deep-learning-multipliers/blob/master/format.py#L61).

Also, as you pointed out, this code is only about low precision _multiplications_.
The reason is that memory accesses and multiplications are much costlier than accumulations, which we explain in the second section of [the article](http://arxiv.org/pdf/1412.7024v5.pdf).

**Comment by stencilman** [comment]
@MatthieuCourbariaux Thanks for your prompt response. I am happy with your explanation for the accumulations.

However, I still have confusion regarding your fixed_point function. Please consider the case:
fixed_point(1000,3,2)    gives me a 3.5. How is this possible with totally 3 bits?

**Comment by MatthieuCourbariaux** [comment]
It is possible because we do not count the sign bit in NOB and NOIB.
2+1+.5 = 3.5

In the article, when we say we are using 10 bit for the computations, we mean 1 bit for the sign and 9 bit for NOB (see Section 9.3). I must admit that it can be confusing, sorry about that.

**Comment by stencilman** [comment]
Oh, I see. Thanks a lot for the explanation!

**Comment by mrsusmith** [comment]
Hi, but still I see some problem there. 
According to https://en.wikipedia.org/wiki/Fixed-point_arithmetic
"The maximum value of a fixed-point type is simply the largest value that can be represented in the underlying integer type multiplied by the scaling factor; and similarly for the minimum value. For example, consider a fixed-point type represented as a binary integer with b bits in two's complement format, with a scaling factor of 1/2f (that is, the last f bits are fraction bits): the minimum representable value is −2^(b−1)/2f and the maximum value is ((2^(b−1))−1))/2f"

Suppose NOB=3, NOIB=2
according to you, |SIGN| I | I |.|F|  where I - integer bit  F - Fraction bit
means 1 sign bit, 2 Integer bit and 1 Fraction bit.
Total 4bit. What is the max it can represent in 2's complement form
0111 to 1000 means, +7 to -8.
Now let's check the calculation.

def fixed_point(X,NOB, NOIB):  
    1. power = T.cast(2.**(NOB - NOIB), theano.config.floatX) # float !
    2. max = T.cast((2.**NOB)-1, theano.config.floatX)
    3. value = X*power  
    4. value = T.round(value) # rounding
    5. value = T.clip(value, -max, max) # saturation arithmetic
    6. value = value/power
    return value
1. power = 2^1
2. max = 2 ^3 - 1 = 7  ( -max = -7 and max = 7 )???
3. value = X \* 2 ( moving to fixed point by left shift 1 )
4. value = round( value) 
5. value = clip ( value , -7, +7 ) ??? clip(value, -8, +7 ) 
 Could you please correct me if i am wrong.?

**Comment by MatthieuCourbariaux** [comment]
> consider a fixed-point type represented as a binary integer with b bits in two's complement format

We are not using two's complement format,
but a simpler format in which 1 bit encodes the sign (and nothing else).
Our simple format thus has two zeros (+0 and -0) , which is useless,
and as you noticed, its range is slightly shorter (in your example [-7,+7] instead of [-8,+7]).

I must admit it was a poor design choice,
and we definitely should have used two's complement format (to have a slightly better range).
That being said, I do not think it is such a big deal when dealing with 10 bits representations.

In any case, thanks for pointing this out :)

**Comment by mrsusmith** [comment]
Ok. Thanks for your time.
